branches:
  only:
    - master

notifications:
  email: false

script: ""

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEYID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "gwt.chrislewisdev.com"
  region: "ap-southeast-2"